apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default include "k8s-event-job.fullname" Values.configMap.name }}
  namespace: {{ Values.namespace }}
data:
  RELOAD_ENABLED: {{ Values.configMap.reloadEnabled }}
  DOCKER_REGISTRY: {{ default "" Values.configMap.dockerRegistry }}
  KUBERNETES_JOB_SCOPE: {{ Values.configMap.jobsNamespace }}
  CONFIG_MAP_NAME: {{ default (printf "%s-%s" include "k8s-event-job.fullname" "jobs") Values.configMap.jobsConfigMapName }}
