apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-event-job.fullname" . }}
  namespace: {{ Values.namespace }}
  labels:
{{ include "k8s-event-job.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "k8s-event-job.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "k8s-event-job.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    spec:
      containers:
        - name: consumer
          image: gocidocker/k8s-event-job:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ default include "k8s-event-job.fullname" Values.configMap.name }}
          - secretRef:
              name: {{ default include "k8s-event-job.fullname" Values.connectSecret.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
