apiVersion: v1
kind: Secret
metadata:
  name: {{ default include "k8s-event-job.fullname" Values.configMap.name }}
  namespace: {{ Values.namespace }}
data:
  AQMP_USERNAME: {{ Values.amqp.username | b64enc }}
  AQMP_PASSWORD: {{ Values.amqp.password | b64enc }}
  AMQP_HOST: {{ Values.amqp.host | b64enc }}
  AMQP_PORT: {{ Values.amqp.port | b64enc }}
