replicaCount: 3

namespace: services

configMap:
  reloadEnabled: true
  jobsNamespace: default
  # jobs: 
  #   my-example-job:
  #     image: docker/image-to-use
  #     imageVersion: 0.1.0
  #     registry: overwrite-docker-registry-to-use
  #     interval: 30
  #     timeout: 600 # includes all restarts
  #     namespace: overwrite-default-jobsNamespace
  #     serviceAccount: optional-sa-name-to-use
  #     environment:
  #     - name: ADDITIONAL_ENV_VAR
  #       value: env-value

amqp:
  port: 5672

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
