name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-16.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build docker image
        run: make build
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Release
        run: make release GITHUB_REF=${{ github.ref }}
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2.1.0
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: gocidocker/kubernetes-event-job
