name: Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-16.04
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build docker image
        run: make build
      - name: Docker login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Release
        run: make release GITHUB_REF=${{ github.ref }}
